const Discord = require('discord.js');
const client = new Discord.Client();
const PREFIX = '/'


client.once('ready', () => {
  console.log('Bot Loaded!')
  });

client.on('message', async message => {
  var server = message.guild

if(server.channels.cache.find(c => c.name == "none-what-noob"))return console.log("New channel not created as it already exists");
  if(!server.channels.cache.find(c => c.name == "【⏸】Current Anime(s)" && c.type == "category"))return console.log("big bad");

  server.channels.create("none-what-noob")
  .then(channel => {
      let category = server.channels.cache.find(c => c.name == "【⏸】Current Anime(s)" && c.type == "category");
    if (!category) throw new Error("Category channel does not exist");
    channel.setParent(category.id);
  }).catch(console.error);

})


client.on('message', async message => {
if(message.content.includes("Episode"))
 await message.react("770277092063445002")
});

client.on('message', message => {
    let args = message.content.substring(PREFIX.length).split(" ")
    switch(args[0]){
      case 'send30':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          message.channel.send('Episode 21')
          message.channel.send('Episode 22')
          message.channel.send('Episode 23')
          message.channel.send('Episode 24')
          message.channel.send('Episode 25')
          message.channel.send('Episode 26')
          message.channel.send('Episode 27')
          message.channel.send('Episode 28')
          message.channel.send('Episode 29')
          message.channel.send('Episode 30')
          break;
          case'send29':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          message.channel.send('Episode 21')
          message.channel.send('Episode 22')
          message.channel.send('Episode 23')
          message.channel.send('Episode 24')
          message.channel.send('Episode 25')
          message.channel.send('Episode 26')
          message.channel.send('Episode 27')
          message.channel.send('Episode 28')
          message.channel.send('Episode 29')
          break;
          case'send28':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          message.channel.send('Episode 21')
          message.channel.send('Episode 22')
          message.channel.send('Episode 23')
          message.channel.send('Episode 24')
          message.channel.send('Episode 25')
          message.channel.send('Episode 26')
          message.channel.send('Episode 27')
          message.channel.send('Episode 28')
          break;
          case'send27':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          message.channel.send('Episode 21')
          message.channel.send('Episode 22')
          message.channel.send('Episode 23')
          message.channel.send('Episode 24')
          message.channel.send('Episode 25')
          message.channel.send('Episode 26')
          message.channel.send('Episode 27')
          break;
          case'send26':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          message.channel.send('Episode 21')
          message.channel.send('Episode 22')
          message.channel.send('Episode 23')
          message.channel.send('Episode 24')
          message.channel.send('Episode 25')
          message.channel.send('Episode 26')
          break;
          case'send25':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          message.channel.send('Episode 21')
          message.channel.send('Episode 22')
          message.channel.send('Episode 23')
          message.channel.send('Episode 24')
          message.channel.send('Episode 25')
          break;
          case'send24':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          message.channel.send('Episode 21')
          message.channel.send('Episode 22')
          message.channel.send('Episode 23')
          message.channel.send('Episode 24')
          break;
          case'send23':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          message.channel.send('Episode 21')
          message.channel.send('Episode 22')
          message.channel.send('Episode 23')
          break;
          case'send22':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          message.channel.send('Episode 21')
          message.channel.send('Episode 22')
          break;
          case'send21':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          message.channel.send('Episode 21')
          break;
          case'send20':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          message.channel.send('Episode 20')
          break;
          case'send19':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          message.channel.send('Episode 19')
          break;
          case'send18':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          message.channel.send('Episode 18')
          break;
          case'send17':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          message.channel.send('Episode 17')
          break;
          case'send16':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          message.channel.send('Episode 16')
          break;
          case'send15':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          message.channel.send('Episode 15')
          break;
          case'send14':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          message.channel.send('Episode 14')
          break;
          case'send13':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          message.channel.send('Episode 13')
          break;
          case'send12':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          message.channel.send('Episode 12')
          break;
          case'send11':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          message.channel.send('Episode 11')
          break;
          case'send10':
          message.channel.send('Episode 1')
          message.channel.send('Episode 2')
          message.channel.send('Episode 3')
          message.channel.send('Episode 4')
          message.channel.send('Episode 5')
          message.channel.send('Episode 6')
          message.channel.send('Episode 7')
          message.channel.send('Episode 8')
          message.channel.send('Episode 9')
          message.channel.send('Episode 10')
          break;
          case'send9':
          message.channel.send('This number is too low for the bot to log episodes with, please try a higher number.')
          case'send8':
          message.channel.send('This number is too low for the bot to log episodes with, please try a higher number.')
          break;
          case'send7':
          message.channel.send('This number is too low for the bot to log episodes with, please try a higher number.')
          break;
          case'send6':
          message.channel.send('This number is too low for the bot to log episodes with, please try a higher number.')
          break;
          case'send5':
          message.channel.send('This number is too low for the bot to log episodes with, please try a higher number.')
          break;
          case'send4':
          message.channel.send('This number is too low for the bot to log episodes with, please try a higher number.')
          break;
          case'send3':
          message.channel.send('This number is too low for the bot to log episodes with, please try a higher number.')
          break;
          case'send2':
          message.channel.send('This number is too low for the bot to log episodes with, please try a higher number.')
          break;
          case'send1':
          message.channel.send('This number is too low for the bot to log episodes with, please try a higher number.')
          break;
          case'send0':
          message.channel.send('There. You happy? You logged 0 episodes, now go study you dumbass.')
          break;
        

    }
}
)
client.login(process.env.token);

